<a href="https://colab.research.google.com/github/mionamash/CIR-203-Assignments/blob/main/Arrays_in_Financial_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
transactions_data=np.array([
    [1200,1500,1600,1800,1700,2000],
    [1000,1100,1150,1200,1250,1300],
    [2000,2100,2200,2300,2400,2500],
    [800,950,1000,1050,1100,1150]
])
print("transactions_data:\n",transactions_data)
total_per_branch=np.sum(transactions_data,axis=1)
print("total_per_branch:\n",total_per_branch)
highest_branch=np.argmax(total_per_branch)+1
print("highest_branch:",highest_branch)
avg_monthly=np.mean(transactions_data,axis=0)
print("avg_monthly:\n",avg_monthly)
reshape=transactions_data.reshape(3,8)
print("Reshaped Array (3×8):\n", reshape)


transactions_data:
 [[1200 1500 1600 1800 1700 2000]
 [1000 1100 1150 1200 1250 1300]
 [2000 2100 2200 2300 2400 2500]
 [ 800  950 1000 1050 1100 1150]]
total_per_branch:
 [ 9800  7000 13500  6050]
highest_branch: 3
avg_monthly:
 [1250.  1412.5 1487.5 1587.5 1612.5 1737.5]
Reshaped Array (3×8):
 [[1200 1500 1600 1800 1700 2000 1000 1100]
 [1150 1200 1250 1300 2000 2100 2200 2300]
 [2400 2500  800  950 1000 1050 1100 1150]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')